SELECT
	NU_ANO,
	NU_AVALIACAO,
	NU_ETAPA,
	NM_DISCIPLINA,
	AVG(VL_PROFICIENCIA) AS VL_MEDIA_PROSA
FROM prosa
WHERE NU_ANO IN (2018, 2019, 2021) AND NU_ETAPA IN (5, 9)
GROUP BY NU_ANO, NU_AVALIACAO, NU_ETAPA, NM_DISCIPLINA;
